In [1]:
import pandas as pd

In [10]:
# (2026-27 start)

import requests

rawText = """
KL - Agr, Consumer & Env Sciences
KY - Applied Health Sciences
LD - Armed Forces
NQ - Auxiliary Units
LT - Carle Illinois Medicine
LN - Center Innov in Teach Learn
NA - Chancellor
KT - College of Media
NU - Div Intercollegiate Athletics
KW - Division of Exploratory Studies
KN - Education
MY - Energy Services
NN - Facilities
KR - Fine & Applied Arts
KM - Gies College of Business
KS - Graduate College
KP - Grainger Engineering
LQ - Illinois International
KU - Law
KV - Liberal Arts & Sciences
NP - OVCRI Institutes
NS - Ofc VC Inst Advancement
NB - Provost & Executive VC
LF - Public Safety
LP - School of Information Sciences
LG - School of Labor & Empl. Rel.
LL - School of Social Work
NT - Technology Services
LR - University Library
NW - VC Administrative Strategy
NL - VC Finance and Administration
NJ - VC Student Affairs
NE - VC for Research and Innovation
LC - Veterinary Medicine
NV - Vice Chancellor for Access
"""

collegeCodes = []
collegeNames = []
for line in rawText.split("\n"):
  if len(line) > 2:
    code, name = line.split(" - ")

    collegeCodes.append(code)
    collegeNames.append(name)

print(collegeCodes)
print(collegeNames)

['KL', 'KY', 'LD', 'NQ', 'LT', 'LN', 'NA', 'KT', 'NU', 'KW', 'KN', 'MY', 'NN', 'KR', 'KM', 'KS', 'KP', 'LQ', 'KU', 'KV', 'NP', 'NS', 'NB', 'LF', 'LP', 'LG', 'LL', 'NT', 'LR', 'NW', 'NL', 'NJ', 'NE', 'LC', 'NV']
['Agr, Consumer & Env Sciences', 'Applied Health Sciences', 'Armed Forces', 'Auxiliary Units', 'Carle Illinois Medicine', 'Center Innov in Teach Learn', 'Chancellor', 'College of Media', 'Div Intercollegiate Athletics', 'Division of Exploratory Studies', 'Education', 'Energy Services', 'Facilities', 'Fine & Applied Arts', 'Gies College of Business', 'Graduate College', 'Grainger Engineering', 'Illinois International', 'Law', 'Liberal Arts & Sciences', 'OVCRI Institutes', 'Ofc VC Inst Advancement', 'Provost & Executive VC', 'Public Safety', 'School of Information Sciences', 'School of Labor & Empl. Rel.', 'School of Social Work', 'Technology Services', 'University Library', 'VC Administrative Strategy', 'VC Finance and Administration', 'VC Student Affairs', 'VC for Research and Innovation', 'Veterinary Medicine', 'Vice Chancellor for Access']

In [14]:
import io

def processPage(rawHTML, collegeCode, collegeName):
  dfs = []
  h3s = rawHTML.split("<h3")
  for index in range(1, len(h3s)):
    h3_split = h3s[index]

    h3_full = "<h3" + h3_split
    h3_split = h3_split[ h3_split.find(">") + 1 : h3_split.find("</h3>") ]
    departmentName = h3_split.split("-")[1].strip()
    print(departmentName)

    df = pd.read_html(io.StringIO(h3_full))[0]
    df["Department Name"] = departmentName
    df["College Code"] = collegeCode
    df["College Name"] = collegeName
    dfs.append(df)

  if len(dfs) > 0:
    return pd.concat(dfs)
  else:
    return None

In [ ]:
# Test script
rawHTML = requests.get(f"https://www.trustees.uillinois.edu/trustees/resources/26-27-Graybook/KP.html").text
rawHTML

processPage(rawHTML, "KP", "Grainger")

Aerospace Engineering
Applied Research Institute
Bioengineering
Civil &amp; Environmental Eng
Coordinated Science Lab
Discovery Partners Inst UIUC
Electrical &amp; Computer Eng
Engineering Administration
Engineering General Expen
Engineering IT Shared Services
Engr Shared Admin Services
Industrial&amp;Enterprise Sys Eng
Information Trust Institute
Landuyt Ctr for Entrprnrshp
Materials Research Lab
Materials Science &amp; Engineerng
Mechanical Sci &amp; Engineering
Micro and Nanotechnology Lab
Nuclear, Plasma, &amp; Rad Engr
Physics
Siebel Center for Design
Siebel School Comp &amp; Data Sci

,Employee Name,Job Title,Tenure,Empl Class,Present FTE,Proposed FTE,Present Salary,Proposed Salary,Department Name,College Code,College Name
0,"Allison, James",PROF,NaN,AA,0.0,0.0,$0.00,$0.00,Aerospace Engineering,KP,Grainger
1,"Allison, James",Employee Total for All Jobs,NaN,NaN,1.0,1.0,"$162,988.29","$169,654.00",Aerospace Engineering,KP,Grainger
2,"Ansell, Phillip J",ASSOC PROF,A,AA,1.0,1.0,"$144,659.42","$153,339.00",Aerospace Engineering,KP,Grainger
3,"Ansell, Phillip J","DIR, CENTER SUSTAIN AVIATION",NaN,BA,0.0,0.0,"$5,000.00","$5,000.00",Aerospace Engineering,KP,Grainger
4,"Ansell, Phillip J",ORMSBEE FACULTY SCHOLAR,NaN,AA,0.0,0.0,$0.00,$0.00,Aerospace Engineering,KP,Grainger
...,...,...,...,...,...,...,...,...,...,...,...
384,"Zhu, Fengyuan",RES ASST PROF,M,AA,1.0,1.0,"$140,000.00","$140,000.00",Siebel School Comp &amp; Data Sci,KP,Grainger
385,"Zike, Heather",ASST DIR UGRAD PRGMS,NaN,BA,1.0,1.0,"$85,850.00","$87,567.00",Siebel School Comp &amp; Data Sci,KP,Grainger
386,"Zilles, Craig",PROF,A,AA,1.0,1.0,"$198,210.48","$204,156.48",Siebel School Comp &amp; Data Sci,KP,Grainger
387,"Zilles, Craig",SEVERNS FAC SCHOLAR,NaN,AA,0.0,0.0,$0.00,$0.00,Siebel School Comp &amp; Data Sci,KP,Grainger
388,"Zilles, Craig",Employee Total for All Jobs,NaN,NaN,1.0,1.0,"$198,210.48","$204,156.48",Siebel School Comp &amp; Data Sci,KP,Grainger

In [20]:
from time import sleep

dfs = []
for i in range(len(collegeCodes)):
  collegeCode = collegeCodes[i]
  collegeName = collegeNames[i]
  print(f"=== {collegeName} ===")
  rawHTML = requests.get(f"https://www.trustees.uillinois.edu/trustees/resources/26-27-Graybook/{collegeCode}.html").text

  result = processPage(rawHTML, collegeCode, collegeName)
  if type(result) is not None:
    dfs.append(result)
  sleep(5)

df = pd.concat(dfs)

=== Agr, Consumer & Env Sciences ===
ACES Technology Services
ADM Institute for PHL
Ag Ldrshp Educ Comm Program
Agr &amp; Consumer Economics
Agr, Consumer &amp; Env Sci Admn
Agricultural &amp; Biological Engr
Animal Sciences
Cooperative Extension
Crop Sciences
Food Science &amp; Human Nutrition
Human Dvlpmt &amp; Family Studies
Natural Res &amp; Env Sci
Nutritional Sciences
<class 'pandas.core.frame.DataFrame'>
=== Applied Health Sciences ===
Applied Health Sciences Admin
Chez Veterans Center
Ctr Health, Aging, Disability
Disability Res &amp; Educ Svcs
Health and Kinesiology
Recreation, Sport and Tourism
Speech &amp; Hearing Science
<class 'pandas.core.frame.DataFrame'>
=== Armed Forces ===
Armed Forces Coordinator
<class 'pandas.core.frame.DataFrame'>
=== Auxiliary Units ===
Aux. Health/WB Marketing
Division of Campus Recreation
Housing Division
Illini Union
McKinley Health Center
Office of the Dean of Students
Parking Department
Student Affairs Technology
<class 'pandas.core.frame.DataFrame'>
=== Carle Illinois Medicine ===
Biomed &amp; Translational Sci
Carle IL COM Administration
Clinical Sciences
Department of Oncology
Dept of Cardio Med and Surg
Dept of Neuro and Neurosurg
Dept of Surg and Digest Health
<class 'pandas.core.frame.DataFrame'>
=== Center Innov in Teach Learn ===
Center Innov in Teach Learn
I
<class 'pandas.core.frame.DataFrame'>
=== Chancellor ===
Faculty/Staff Assistance Svcs
Illinois Human Resources
News Bureau
Office of the Chancellor
Special Events
StratCommunications
Web Services
<class 'pandas.core.frame.DataFrame'>
=== College of Media ===
Advertising
College of Media Admin
IPM Administration
IPM Content Information
IPM Content Production
IPM Content Programming
IPM Delivery
IPM Development
Inst of Communications Rsch
Journalism
Media and Cinema Studies
<class 'pandas.core.frame.DataFrame'>
=== Div Intercollegiate Athletics ===
Intercollegiate Athletics
State Farm Center
<class 'pandas.core.frame.DataFrame'>
=== Division of Exploratory Studies ===
Center Advising &amp; Acad Svcs
<class 'pandas.core.frame.DataFrame'>
=== Education ===
Bureau Educational Research
Centers &amp;Strategic Initiatives
Council Teacher Ed Admin
Curriculum and Instruction
Educ Policy, Orgzn &amp; Leadrshp
Education Administration
Educational Psychology
Special Education
<class 'pandas.core.frame.DataFrame'>
=== Energy Services ===
Energy Management Services
<class 'pandas.core.frame.DataFrame'>
=== Facilities ===
Bldg Maintenance Crafts/Trades
F&amp;S Engineering Services
Facilities and Services
<class 'pandas.core.frame.DataFrame'>
=== Fine & Applied Arts ===
Architecture
Art &amp; Design
Dance
Fine &amp; Applied Arts Admin
Japan House
Krannert Art Museum
Krannert Center
Landscape Architecture
Music
Theatre
Urban &amp; Regional Planning
<class 'pandas.core.frame.DataFrame'>
=== Gies College of Business ===
Accountancy
Business Administration
Content &amp; Ed PortfolioStrategy
Ctr Business &amp; Public Policy
Finance
Gies Access and Engagement
Gies Advancement
Gies Business Grad Programs
Gies College of Business
Gies Global Programs
Gies Graduate Programs
Gies Mktg &amp; Communications
Gies Undergraduate Programs
GiesResearch&amp;FacultyExcellence
IT Partners Gies Business
Illinois Business Consulting
Innovation &amp; Transformation
OV Office of Entrepreneurship
Office of Access and Community
Student &amp; Corporate Connection
Teaching and Learning
<class 'pandas.core.frame.DataFrame'>
=== Graduate College ===
Graduate Admin
Professional Education
<class 'pandas.core.frame.DataFrame'>
=== Grainger Engineering ===
Aerospace Engineering
Applied Research Institute
Bioengineering
Civil &amp; Environmental Eng
Coordinated Science Lab
Discovery Partners Inst UIUC
Electrical &amp; Computer Eng
Engineering Administration
Engineering General Expen
Engineering IT Shared Services
Engr Shared Admin Services
Industrial&amp;Enterprise Sys Eng
Information Trust Institute
Landuyt Ctr for Entrprnrshp
Materials Research Lab
Materials Science &amp; Engineerng
Mechanical Sci &amp; Engineering
Micro and Nanotechnology Lab
Nuclear, Plasma, &amp; Rad Engr
Physics
Siebel Center for Design
Siebel School Comp &amp; Data Sci
<class 'pandas.core.frame.DataFrame'>
=== Illinois International ===
Global Education &amp; Training
Illinois Abroad
Illinois International
Intensive English Institute
Intl Student and Scholar Svcs
<class 'pandas.core.frame.DataFrame'>
=== Law ===
Law
Law Library
<class 'pandas.core.frame.DataFrame'>
=== Liberal Arts & Sciences ===
Actuarial Sci and Risk Mgmt
African American Studies
American Indian Studies Prgrm
Anthropology
Appl Tech Learning Arts &amp; Sciences
Asian American Studies
Astronomy
Biochemistry
Biophysics &amp; Quant Biology
Cell &amp; Developmental Biology
Center for African Studies
Center for Global Studies
Center for Writing Studies
Chemical &amp; Biomolecular Engr
Chemistry
Classics
Climate Meteorology &amp; Atm Sci
Cline Ctr for Adv Social Rsrch
Communication
Comparative &amp; World Literature
Ctr S. Asian &amp; MidEast Studies
E Asian &amp; Pacific Studies Cntr
E. Asian Languages &amp; Cultures
Earth Sci &amp; Environmental Chng
Economics
English
Entomology
European Union Center
Evolution Ecology Behavior
French and Italian
Gender and Women's Studies
Geography &amp; GIS
Germanic Languages &amp; Lit
Global Studies Prog &amp; Courses
History
Illinois Global Institute
LAS Administration
Latin American &amp; Carib Studies
Latina/Latino Studies
Lemann Center
Linguistics
Mathematics
Microbiology
Molecular &amp; Integrative Physl
Neuroscience Program
Philosophy
Plant Biology
Political Science
Prg in Jewish Culture &amp;Society
Program in Medieval Studies
Psychology
Religion
Russian,E European,Eurasn Ctr
Sch Earth, Soc, Environ Admin
Sch Lit, Cultures, Ling Adm
School of Chemical Sciences
School of Integrative Biology
School of Molecular &amp; Cell Bio
Slavic Languages &amp; Literature
Sociology
Spanish and Portuguese
Spurlock Museum
Statistics
Study of Global Gender Equity
The ACDIS Program
Translation &amp; Interpreting St
Unit For Criticism
<class 'pandas.core.frame.DataFrame'>
=== OVCRI Institutes ===
Beckman Institute
Cancer Center at Illinois
Humanities Research Institute
IL Natural History Survey
IL State Archaeological Survey
IL State Geological Survey
IL State Water Survey
IL Sustainable Technology Ctr
Inst for Sustain, Enrgy, &amp; Env
Institute for Genomic Biology
Interdis Health Sci Institute
Prairie Research Institute
Social Behavioral Science Inst
Supercomputing Applications
<class 'pandas.core.frame.DataFrame'>
=== Ofc VC Inst Advancement ===
Ofc VC Inst Advancement
<class 'pandas.core.frame.DataFrame'>
=== Provost & Executive VC ===
Big Ten Academic Alliance
Campus Honors Program
Center for Advanced Study
Data, Analytics &amp; IR
Enrollment Mgmt Shared Svcs
Office of Undergrad Research
Office of the Registrar
Osher Lifelong Learning Inst
Principal's Scholars Pgm
Provost/EVC Admin
Student Financial Aid
Undergraduate Admissions
University Laboratory HS
<class 'pandas.core.frame.DataFrame'>
=== Public Safety ===
Fire Service Institute
<class 'pandas.core.frame.DataFrame'>
=== School of Information Sciences ===
Informatics
Information Sciences
<class 'pandas.core.frame.DataFrame'>
=== School of Labor & Empl. Rel. ===
School of Labor &amp; Empl. Rel.
<class 'pandas.core.frame.DataFrame'>
=== School of Social Work ===
School of Social Work
<class 'pandas.core.frame.DataFrame'>
=== Technology Services ===
Campus Research IT
Ofc of the Chief Info Officer
Technology Services
<class 'pandas.core.frame.DataFrame'>
=== University Library ===
Library
Library Admin
Library Collections/Support
Library Research &amp; Publication
Mortenson Cntr Int'l Lib Prgms
<class 'pandas.core.frame.DataFrame'>
=== VC Administrative Strategy ===
Chief of Staff
Ofc of Strategic Project Mgmt
<class 'pandas.core.frame.DataFrame'>
=== VC Finance and Administration ===
Admin and Operations
Allerton Park &amp; Retreat Center
Division of Public Safety
Finance Budget &amp; Planning
Illini Center
Office of Threat Assessment
Police Training Institute
Willard Airport Commercial Op
<class 'pandas.core.frame.DataFrame'>
=== VC Student Affairs ===
Counseling Center
Illinois Leadership Center
Jeffries Ctr Acces and AcadSuc
SmartHealthyCommunity(Rokwire)
Student Conflict Resolution
Student Success, Incl &amp; Belong
The Career Center
VC Student Affairs
<class 'pandas.core.frame.DataFrame'>
=== VC for Research and Innovation ===
Animal Care Program
Biotechnology Center
Division of Research Safety
EnterpriseWorks
IL Quantum &amp; Microelec Park
OVCRI Admin
Office of Animal Research Comp
Office of Corporate Relations
Office of Proposal Development
Office of Research Security
Protection of Research Subject
Sponsored Programs Admin
<class 'pandas.core.frame.DataFrame'>
=== Veterinary Medicine ===
Center for Zoonoses Research
Comparative Biosciences
Medical District Vet Clinic
Pathobiology
Vet Clinical Medicine
Vet Med College
Vet Medicine Administration
Veterinary Diagnostic Lab
Veterinary Prog in Agr
Veterinary Teaching Hospital
<class 'pandas.core.frame.DataFrame'>
=== Vice Chancellor for Access ===
Civil Rights Coords Admin
Office for Access and Equity
Vice Chancellor for Access
<class 'pandas.core.frame.DataFrame'>

In [21]:
df["Proposed Salary"] = df["Proposed Salary"].replace('[\$,]', '', regex=True).astype(float)

In [22]:
df["Present Salary"] = df["Present Salary"].replace('[\$,]', '', regex=True).astype(float)

In [23]:
df["Department Name"] = df["Department Name"].str.replace('&amp;', '&')

In [24]:
df["College Name"] = df["College Name"].replace('&amp;', '&')

In [27]:
df[ df["Employee Name"] == "Kumar, Praveen" ]

,Employee Name,Job Title,Tenure,Empl Class,Present FTE,Proposed FTE,Present Salary,Proposed Salary,Department Name,College Code,College Name
69,"Kumar, Praveen",PROF,A,AA,1.0,1.0,248071.08,254283.00,Civil & Environmental Eng,KP,Grainger Engineering
70,"Kumar, Praveen",Employee Total for All Jobs,NaN,NaN,1.0,1.0,288071.08,294283.00,Civil & Environmental Eng,KP,Grainger Engineering
154,"Kumar, Praveen","CLIN PROF, HCESC",NaN,AL,0.0,0.0,0.00,0.00,Coordinated Science Lab,KP,Grainger Engineering
155,"Kumar, Praveen",Employee Total for All Jobs,NaN,NaN,1.0,1.0,422438.56,426662.94,Coordinated Science Lab,KP,Grainger Engineering
18,"Kumar, Praveen",DEPT AFFL,NaN,AA,0.0,0.0,0.00,0.00,Climate Meteorology & Atm Sci,KV,Liberal Arts & Sciences
19,"Kumar, Praveen",Employee Total for All Jobs,NaN,NaN,1.0,1.0,288071.08,294283.00,Climate Meteorology & Atm Sci,KV,Liberal Arts & Sciences
69,"Kumar, Praveen","PROF, ISEE",NaN,AA,0.0,0.0,0.00,0.00,"Inst for Sustain, Enrgy, & Env",NP,OVCRI Institutes
70,"Kumar, Praveen",Employee Total for All Jobs,NaN,NaN,1.0,1.0,288071.08,294283.00,"Inst for Sustain, Enrgy, & Env",NP,OVCRI Institutes
10,"Kumar, Praveen","EXEC DIR, PRI",NaN,BA,0.0,0.0,40000.00,40000.00,Prairie Research Institute,NP,OVCRI Institutes
11,"Kumar, Praveen",Employee Total for All Jobs,NaN,NaN,1.0,1.0,288071.08,294283.00,Prairie Research Institute,NP,OVCRI Institutes
240,"Kumar, Praveen","PROF, NCSA",NaN,AA,0.0,0.0,0.00,0.00,Supercomputing Applications,NP,OVCRI Institutes
241,"Kumar, Praveen",Employee Total for All Jobs,NaN,NaN,1.0,1.0,288071.08,294283.00,Supercomputing Applications,NP,OVCRI Institutes

In [28]:
def process(dfE):
  df_jobs = dfE[ dfE["Job Title"] != "Employee Total for All Jobs" ]
  
  jobTitles = list(df_jobs["Job Title"].unique())
  depts = list(df_jobs["Department Name"].unique())
  
  highest_salary_row = df_jobs.nlargest(1, "Proposed Salary")
  jobTitles.remove(highest_salary_row["Job Title"].values[0])
  depts.remove(highest_salary_row["Department Name"].values[0])

  if len(jobTitles) == 0:
    jobTitles = ""
  if len(depts) == 0:
    depts = ""

  return {
    "Employee Name": highest_salary_row["Employee Name"].values[0],

    "Primary Job Title": highest_salary_row["Job Title"].values[0],
    "Department Name": highest_salary_row["Department Name"].values[0],
    "College Code": highest_salary_row["College Code"].values[0],
    "College Name": highest_salary_row["College Name"].values[0],

    "Present FTE": dfE["Present FTE"].max(),
    "Proposed FTE": dfE["Proposed FTE"].max(),
    "Present Salary": dfE["Present Salary"].max(),
    "Proposed Salary": dfE["Proposed Salary"].max(),

    "Tenure": highest_salary_row["Tenure"].values[0],
    "Empl Class": highest_salary_row["Empl Class"].values[0],

    "Secondary Job Titles": str(jobTitles),
    "Secondary Department Names": str(depts),
  }


d = []
for name in df["Employee Name"].unique():
  dfSingle = df[ df["Employee Name"] == name ]

  dfAllJobs = dfSingle[ dfSingle["Job Title"] == "Employee Total for All Jobs" ]

  if len(dfAllJobs) > 1:
    values = dfAllJobs["Present Salary"].values

    val = values[0]
    identicalName = False
    for v in values:
      if v != val:
        identicalName = True

    if identicalName:
      if name == "Kumar, Praveen":
        indexFilter = [154, 155]
      else:
        print(f"!!! {name}")
        
      df1 = dfSingle[ dfSingle.index.isin(indexFilter) ]
      df2 = dfSingle[ ~dfSingle.index.isin(indexFilter) ]

      d.append(process(df1))
      d.append(process(df2))
    else:
      d.append(process(dfSingle))
  else:
    d.append(process(dfSingle))

In [29]:
df_CLEAN = pd.DataFrame(d)

In [30]:
df.head(30)

,Employee Name,Job Title,Tenure,Empl Class,Present FTE,Proposed FTE,Present Salary,Proposed Salary,Department Name,College Code,College Name
0,"Kim, James H",DIR OF INFO TECHNOL,NaN,BA,1.0,1.0,116150.00,118473.00,ACES Technology Services,KL,"Agr, Consumer & Env Sciences"
1,"Meyer, Donald L",SR NETWORK ANLYS,NaN,BA,1.0,1.0,99311.76,101000.06,ACES Technology Services,KL,"Agr, Consumer & Env Sciences"
0,"McNamara, Paul E","DIR, ADMI",NaN,BA,0.0,0.0,15000.00,15000.00,ADM Institute for PHL,KL,"Agr, Consumer & Env Sciences"
1,"McNamara, Paul E",Employee Total for All Jobs,NaN,NaN,1.0,1.0,175541.92,183569.02,ADM Institute for PHL,KL,"Agr, Consumer & Env Sciences"
0,"Axtman-Barker, Pamela Ann",TCH ASST PROF,NaN,AL,1.0,1.0,83148.00,87164.05,Ag Ldrshp Educ Comm Program,KL,"Agr, Consumer & Env Sciences"
1,"Botkin, Haden Myles",ASST PROF,NaN,AA,1.0,1.0,88000.00,91080.00,Ag Ldrshp Educ Comm Program,KL,"Agr, Consumer & Env Sciences"
2,"Botkin, Haden Myles",Employee Total for All Jobs,NaN,NaN,1.0,1.0,88000.00,91080.00,Ag Ldrshp Educ Comm Program,KL,"Agr, Consumer & Env Sciences"
3,"Korte, Debra Sue",TCH ASSOC PROF,M,AA,1.0,1.0,105332.83,108492.82,Ag Ldrshp Educ Comm Program,KL,"Agr, Consumer & Env Sciences"
4,"Korte, Debra Sue",Employee Total for All Jobs,NaN,NaN,1.0,1.0,105332.83,108492.82,Ag Ldrshp Educ Comm Program,KL,"Agr, Consumer & Env Sciences"
5,"Leman, Amy Marie",ASST PROF,NaN,AA,1.0,1.0,93665.82,96007.47,Ag Ldrshp Educ Comm Program,KL,"Agr, Consumer & Env Sciences"
6,"Leman, Amy Marie",Employee Total for All Jobs,NaN,NaN,1.0,1.0,93665.82,96007.47,Ag Ldrshp Educ Comm Program,KL,"Agr, Consumer & Env Sciences"
7,"Marzolino, Tiffany Anne",ASST PROF,NaN,AA,1.0,1.0,91000.00,92820.00,Ag Ldrshp Educ Comm Program,KL,"Agr, Consumer & Env Sciences"
8,"Marzolino, Tiffany Anne",Employee Total for All Jobs,NaN,NaN,1.0,1.0,91000.00,92820.00,Ag Ldrshp Educ Comm Program,KL,"Agr, Consumer & Env Sciences"
9,"Morgan, Eric Lee",ASSOC PROF,NaN,AA,1.0,1.0,97771.20,99726.62,Ag Ldrshp Educ Comm Program,KL,"Agr, Consumer & Env Sciences"
10,"Morgan, Eric Lee",Employee Total for All Jobs,NaN,NaN,1.0,1.0,97771.20,99726.62,Ag Ldrshp Educ Comm Program,KL,"Agr, Consumer & Env Sciences"
11,"Ochs, Gary Alan",INSTR,NaN,AL,1.0,1.0,87371.95,89119.39,Ag Ldrshp Educ Comm Program,KL,"Agr, Consumer & Env Sciences"
12,"Roady, Amy Marie","DIR, EVANS CTR FOOD&AGRI COMNC",NaN,BA,0.0,0.0,0.00,0.00,Ag Ldrshp Educ Comm Program,KL,"Agr, Consumer & Env Sciences"
13,"Roady, Amy Marie",INSTRUCTOR,NaN,AA,1.0,1.0,73650.00,73650.00,Ag Ldrshp Educ Comm Program,KL,"Agr, Consumer & Env Sciences"
14,"Roady, Amy Marie",Employee Total for All Jobs,NaN,NaN,1.0,1.0,73650.00,73650.00,Ag Ldrshp Educ Comm Program,KL,"Agr, Consumer & Env Sciences"
15,"Rosch, David Michael",ASSOC PROF,NaN,AA,1.0,1.0,109308.73,113954.35,Ag Ldrshp Educ Comm Program,KL,"Agr, Consumer & Env Sciences"
16,"Rosch, David Michael",Employee Total for All Jobs,NaN,NaN,1.0,1.0,109308.73,113954.35,Ag Ldrshp Educ Comm Program,KL,"Agr, Consumer & Env Sciences"
17,"Smist, Jennifer Anne",TCH ASST PROF,NaN,AL,1.0,1.0,94232.28,97530.41,Ag Ldrshp Educ Comm Program,KL,"Agr, Consumer & Env Sciences"
18,"Wirz, Christopher Dean",ASST PROF,NaN,AA,1.0,1.0,88000.00,91080.00,Ag Ldrshp Educ Comm Program,KL,"Agr, Consumer & Env Sciences"
19,"Wirz, Christopher Dean",Employee Total for All Jobs,NaN,NaN,1.0,1.0,88000.00,91080.00,Ag Ldrshp Educ Comm Program,KL,"Agr, Consumer & Env Sciences"
0,"Arends-Kuenning, Mary Paula",PROF,A,AA,1.0,1.0,155988.44,159108.21,Agr & Consumer Economics,KL,"Agr, Consumer & Env Sciences"
1,"Arends-Kuenning, Mary Paula",Employee Total for All Jobs,NaN,NaN,1.0,1.0,175988.44,179108.21,Agr & Consumer Economics,KL,"Agr, Consumer & Env Sciences"
2,"Atallah, Shady Salim",ASSOC PROF,A,AA,1.0,1.0,156279.82,167219.41,Agr & Consumer Economics,KL,"Agr, Consumer & Env Sciences"
3,"Atallah, Shady Salim",Employee Total for All Jobs,NaN,NaN,1.0,1.0,156279.82,167219.41,Agr & Consumer Economics,KL,"Agr, Consumer & Env Sciences"
4,"Baltz, James H",CMPUT ASST INST SPEC,NaN,BA,1.0,1.0,92900.53,94758.54,Agr & Consumer Economics,KL,"Agr, Consumer & Env Sciences"
5,"Batts, Ryan M","EXT SPEC, FARM & FIN MGMT",NaN,BA,1.0,1.0,60330.11,64553.22,Agr & Consumer Economics,KL,"Agr, Consumer & Env Sciences"

In [31]:
df_CLEAN.to_csv("graybook-fa26.csv", index=False)

In [34]:
df_CLEAN[ df_CLEAN["Employee Name"].str.startswith("Flanagan")]

,Employee Name,Primary Job Title,Department Name,College Code,College Name,Present FTE,Proposed FTE,Present Salary,Proposed Salary,Tenure,Empl Class,Secondary Job Titles,Secondary Department Names
3846,"Flanagan, Ryan P",SR LECTURER,English,KV,Liberal Arts & Sciences,1.0,1.0,64050.69,65331.70,NaN,AA,,
4022,"Flanagan, Karle Ann",TCH ASSOC PROF,Statistics,KV,Liberal Arts & Sciences,1.0,1.0,122685.83,125728.35,M,AA,['DIR INCLSV DATA SCI ED'],['LAS Administration']

<hr>

In [6]:
df_college = pd.read_html(url)
df_college

[               Employee Name                     Job Title Tenure Empl Class  \
 0             Allison, James                    ASSOC PROF    NaN         AA
 1             Allison, James   Employee Total for All Jobs    NaN        NaN
 2          Ansell, Phillip J                    ASSOC PROF      A         AA
 3          Ansell, Phillip J  DIR, CENTER SUSTAIN AVIATION    NaN         BA
 4          Ansell, Phillip J   Employee Total for All Jobs    NaN        NaN
 ..                       ...                           ...    ...        ...
 88  Woollands, Robyn Michele                     ASST PROF      P         AA
 89  Woollands, Robyn Michele   Employee Total for All Jobs    NaN        NaN
 90   Wroblewski, Gabrielle E                 TCH ASST PROF      M         AA
 91        Zahedi Mehr, Negar                     ASST PROF      P         AA
 92        Zahedi Mehr, Negar   Employee Total for All Jobs    NaN        NaN

     Present FTE  Proposed FTE Present Salary Proposed Salary
 0           0.0           0.0          $0.00           $0.00
 1           1.0           1.0    $122,876.00     $127,901.00
 2           1.0           1.0    $125,439.00     $132,298.00
 3           0.0           0.0      $5,000.00       $5,000.00
 4           1.0           1.0    $130,439.00     $137,298.00
 ..          ...           ...            ...             ...
 88          1.0           1.0    $106,250.00     $110,500.00
 89          1.0           1.0    $106,250.00     $110,500.00
 90          1.0           1.0     $80,000.00      $83,200.00
 91          1.0           1.0    $107,782.00     $112,093.00
 92          1.0           1.0    $107,782.00     $112,093.00

 [93 rows x 8 columns],
                    Employee Name                    Job Title  Tenure  \
 0            Aboukhatwa, Mohamed                   SR RES SCI     NaN
 1      Bernhard, Jennifer Truman                     DIR, ARI     NaN
 2      Bernhard, Jennifer Truman  Employee Total for All Jobs     NaN
 3         Colina Morles, Eliezer                  SR RES ENGR     NaN
 4         Dalhaus, Jessica Lynne             ASST DIR FOR RES     NaN
 5           Ehrhardt, David Adam                  SR RES ENGR     NaN
 6            Elabd, Omar Mohamed             SR SOFTWARE ENGR     NaN
 7                 Eslami, Maryam                STAFF RES SCI     NaN
 8                  Fallaw, James             SR SOFTWARE ENGR     NaN
 9      Johnson, Nicole Eddington                 MANAGING DIR     NaN
 10      Krogstad, Daniel Vincent                   SR RES SCI     NaN
 11      Krogstad, Daniel Vincent  Employee Total for All Jobs     NaN
 12                    Lucic, Ana                STAFF RES SCI     NaN
 13             Ondrejcek, Michal             SR SOFTWARE ENGR     NaN
 14  Timmons, Alexandra Christina               STAFF RES ENGR     NaN
 15             Witmer, Ann-Perry                   SR RES SCI     NaN
 16             Witmer, Ann-Perry  Employee Total for All Jobs     NaN

    Empl Class  Present FTE  Proposed FTE Present Salary Proposed Salary
 0          BA          1.0           1.0    $109,772.00     $113,888.00
 1          BA          0.0           0.0     $15,000.00      $15,000.00
 2         NaN          1.0           1.0    $233,026.00     $241,751.00
 3          BA          1.0           1.0    $108,212.00     $111,458.00
 4          BA          1.0           1.0     $84,000.00      $87,360.00
 5          BA          1.0           1.0    $121,699.00     $126,263.00
 6          BA          1.0           1.0    $103,179.00     $107,564.00
 7          BA          1.0           1.0     $92,000.00      $95,680.00
 8          BA          1.0           1.0     $96,000.00      $99,360.00
 9          BA          1.0           1.0    $147,280.00     $154,644.00
 10         BA          1.0           1.0    $110,240.00     $116,854.00
 11        NaN          1.0           1.0    $110,240.00     $116,854.00
 12         BA          1.0           1.0     $95,319.00      $99,370.00
 13         BA          1.0           1.0     $93,000.00      $96,720.00
 14         BA          1.0           1.0     $70,875.00      $75,801.00
 15         BA          1.0           1.0    $103,966.00     $107,085.00
 16        NaN          1.0           1.0    $103,966.00     $107,085.00  ,
                       Employee Name                    Job Title Tenure  \
 0              Aksimentiev, Aleksei                         PROF    NaN
 1              Aksimentiev, Aleksei  Employee Total for All Jobs    NaN
 2                    Amos, Jennifer          DIR OF M.ENG. PRGMS    NaN
 3                    Amos, Jennifer         HAHN FACULTY SCHOLAR    NaN
 4                    Amos, Jennifer                TEACHING PROF      M
 ..                              ...                          ...    ...
 167                Zhao, Sihai Dave  Employee Total for All Jobs    NaN
 168                      Zhao, Yang                    ASST PROF    NaN
 169                      Zhao, Yang  Employee Total for All Jobs    NaN
 170  van der Donk, Wilfred Adrianus                         PROF    NaN
 171  van der Donk, Wilfred Adrianus  Employee Total for All Jobs    NaN

     Empl Class  Present FTE  Proposed FTE Present Salary Proposed Salary
 0           AA          0.0           0.0          $0.00           $0.00
 1          NaN          1.0           1.0    $141,698.00     $148,783.00
 2           BA          0.0           0.0      $5,000.00       $5,000.00
 3           AA          0.0           0.0          $0.00           $0.00
 4           AA          1.0           1.0    $119,756.00     $125,558.00
 ..         ...          ...           ...            ...             ...
 167        NaN          1.0           1.0    $135,475.46     $141,247.33
 168         AA          0.0           0.0          $0.00           $0.00
 169        NaN          1.0           1.0    $121,835.00     $127,266.00
 170         AA          0.0           0.0          $0.00           $0.00
 171        NaN          1.0           1.0    $281,681.54     $292,667.12

 [172 rows x 8 columns],
                 Employee Name                    Job Title Tenure Empl Class  \
 0             Al-Qadi, Imad L                   DIR, ATREL    NaN         BA
 1             Al-Qadi, Imad L                         PROF      A         AA
 2             Al-Qadi, Imad L  Employee Total for All Jobs    NaN        NaN
 3    Alipour Tabrizi, Mohamad                RES ASST PROF      M         AA
 4          Andrawes, Bassem O                         PROF      A         AA
 ..                        ...                          ...    ...        ...
 138            Zhang, Xiaojia                    ASST PROF      P         AA
 139            Zhang, Xiaojia         CRAWFORD FAC SCHOLAR    NaN         AA
 140            Zhang, Xiaojia  Employee Total for All Jobs    NaN        NaN
 141                 Zhao, Lei                    ASST PROF      P         AA
 142                 Zhao, Lei  Employee Total for All Jobs    NaN        NaN

      Present FTE  Proposed FTE Present Salary Proposed Salary
 0            0.0           0.0      $5,000.00       $5,000.00
 1            1.0           1.0    $261,403.00     $271,859.00
 2            1.0           1.0    $276,403.00     $286,859.00
 3            1.0           1.0     $99,275.00     $103,246.00
 4            1.0           1.0    $156,758.00     $167,596.00
 ..           ...           ...            ...             ...
 138          1.0           1.0    $110,823.00     $116,756.00
 139          0.0           0.0          $0.00           $0.00
 140          1.0           1.0    $110,823.00     $116,756.00
 141          1.0           1.0    $110,282.00     $114,693.00
 142          1.0           1.0    $110,282.00     $114,693.00

 [143 rows x 8 columns],
   Employee Name                    Job Title  Tenure Empl Class  Present FTE  \
 0   Olson, Luke                     DIR, CSE     NaN         BA          0.0
 1   Olson, Luke  Employee Total for All Jobs     NaN        NaN          1.0

    Proposed FTE Present Salary Proposed Salary
 0           0.0     $15,000.00      $15,000.00
 1           1.0    $215,000.00     $223,000.00  ,
              Employee Name                     Job Title Tenure Empl Class  \
 0        Abdelzaher, Tarek                          PROF      A         AA
 1        Abdelzaher, Tarek   Employee Total for All Jobs    NaN        NaN
 2           Adve, Sarita V                          PROF      A         AA
 3           Adve, Sarita V   Employee Total for All Jobs    NaN        NaN
 4    Adve, Vikram Sadanand                          PROF      A         AA
 ..                     ...                           ...    ...        ...
 308              Zhao, Han   Employee Total for All Jobs    NaN        NaN
 309          Zike, Heather  UGRAD PRGM COORD & ACAD ADVR    NaN         BA
 310          Zilles, Craig                          PROF      A         AA
 311          Zilles, Craig           SEVERNS FAC SCHOLAR    NaN         AA
 312          Zilles, Craig   Employee Total for All Jobs    NaN        NaN

      Present FTE  Proposed FTE Present Salary Proposed Salary
 0            1.0           1.0    $220,000.00     $228,800.00
 1            1.0           1.0    $220,000.00     $228,800.00
 2            1.0           1.0    $230,000.00     $240,000.00
 3            1.0           1.0    $230,000.00     $240,000.00
 4            1.0           1.0    $230,000.00     $240,000.00
 ..           ...           ...            ...             ...
 308          1.0           1.0    $136,000.00     $141,440.00
 309          1.0           1.0     $65,487.40      $68,106.40
 310          1.0           1.0    $185,000.00     $192,400.00
 311          0.0           0.0          $0.00           $0.00
 312          1.0           1.0    $185,000.00     $192,400.00

 [313 rows x 8 columns],
              Employee Name                    Job Title  Tenure Empl Class  \
 0        Abdelzaher, Tarek                    PROF, CSL     NaN         AA
 1        Abdelzaher, Tarek  Employee Total for All Jobs     NaN        NaN
 2           Adve, Sarita V                    PROF, CSL     NaN         AA
 3           Adve, Sarita V  Employee Total for All Jobs     NaN        NaN
 4    Adve, Vikram Sadanand                    PROF, CSL     NaN         AA
 ..                     ...                          ...     ...        ...
 291      Zhang, Richard Yi  Employee Total for All Jobs     NaN        NaN
 292          Zhao, Zhizhen              ASSOC PROF, CSL     NaN         AA
 293          Zhao, Zhizhen  Employee Total for All Jobs     NaN        NaN
 294      Zharnitsky, Vadim                    PROF, CSL     NaN         AA
 295      Zharnitsky, Vadim  Employee Total for All Jobs     NaN        NaN

      Present FTE  Proposed FTE Present Salary Proposed Salary
 0            0.0           0.0          $0.00           $0.00
 1            1.0           1.0    $220,000.00     $228,800.00
 2            0.0           0.0          $0.00           $0.00
 3            1.0           1.0    $230,000.00     $240,000.00
 4            0.0           0.0          $0.00           $0.00
 ..           ...           ...            ...             ...
 291          1.0           1.0    $121,695.00     $126,908.00
 292          0.0           0.0          $0.00           $0.00
 293          1.0           1.0    $150,000.00     $156,003.00
 294          0.0           0.0          $0.00           $0.00
 295          1.0           1.0    $110,988.04     $114,839.32

 [296 rows x 8 columns],
       Employee Name                    Job Title Tenure Empl Class  \
 0    Adve, Sarita V                         PROF    NaN         AA
 1    Adve, Sarita V  Employee Total for All Jobs    NaN        NaN
 2     Aggarwal, Anu                TCH ASST PROF      M         AA
 3       Allen, Jont                         PROF      A         AA
 4       Allen, Jont  Employee Total for All Jobs    NaN        NaN
 ..              ...                          ...    ...        ...
 369   Zhao, Zhizhen                   ASSOC PROF      A         AA
 370   Zhao, Zhizhen       EVERITT FACULTY FELLOW    NaN         AA
 371   Zhao, Zhizhen  Employee Total for All Jobs    NaN        NaN
 372    Zhu, Wenjuan                   ASSOC PROF      A         AA
 373    Zhu, Wenjuan  Employee Total for All Jobs    NaN        NaN

      Present FTE  Proposed FTE Present Salary Proposed Salary
 0            0.0           0.0          $0.00           $0.00
 1            1.0           1.0    $230,000.00     $240,000.00
 2            1.0           1.0     $97,951.00     $102,269.00
 3            1.0           1.0    $147,392.00     $151,322.00
 4            1.0           1.0    $147,392.00     $151,322.00
 ..           ...           ...            ...             ...
 369          1.0           1.0    $150,000.00     $156,003.00
 370          0.0           0.0          $0.00           $0.00
 371          1.0           1.0    $150,000.00     $156,003.00
 372          1.0           1.0    $133,630.00     $138,971.00
 373          1.0           1.0    $133,630.00     $138,971.00

 [374 rows x 8 columns],
             Employee Name                    Job Title  Tenure Empl Class  \
 0          Ahmad, Irfan S     EXEC DIR, INTERDISC INIT     NaN         BA
 1          Ahmad, Irfan S  Employee Total for All Jobs     NaN        NaN
 2         Al-Qadi, Imad L  DIR, SMART TRANS INFRA INIT     NaN         BA
 3         Al-Qadi, Imad L  Employee Total for All Jobs     NaN        NaN
 4    Albers, Stacey Lynne                    ACAD ADVR     NaN         BA
 ..                    ...                          ...     ...        ...
 132    Wright, Ashleigh R   ASSOC DIR OF INST FOR IDEA     NaN         BA
 133        Zhang, Yuanhui                         PROF     NaN         AA
 134        Zhang, Yuanhui  Employee Total for All Jobs     NaN        NaN
 135     Zollinger, Jana M                DIR OF ADVCMT     NaN         BA
 136     Zollinger, Jana M  Employee Total for All Jobs     NaN        NaN

      Present FTE  Proposed FTE Present Salary Proposed Salary
 0            1.0           1.0    $169,447.00     $174,522.00
 1            1.0           1.0    $169,447.00     $174,522.00
 2            0.0           0.0     $10,000.00      $10,000.00
 3            1.0           1.0    $276,403.00     $286,859.00
 4            1.0           1.0     $57,000.00      $57,000.00
 ..           ...           ...            ...             ...
 132          1.0           1.0    $104,500.00     $107,635.00
 133          0.0           0.0          $0.00           $0.00
 134          1.0           1.0    $178,280.79     $185,112.02
 135          0.5           0.5     $53,303.00      $55,702.00
 136          1.0           1.0    $106,606.00     $111,404.00

 [137 rows x 8 columns],
      Employee Name                Job Title  Tenure Empl Class  Present FTE  \
 0  Block, Daniel J  ENGR TEACHING LAB COORD     NaN         BA          1.0

    Proposed FTE Present Salary Proposed Salary
 0           1.0    $102,500.00     $106,600.00  ,
                    Employee Name                      Job Title  Tenure  \
 0       Bequette, Kaitlyn Louise                STUD EMPL COORD     NaN
 1   Booth, Kathleen Sharon Ervin                      BUS ANLYS     NaN
 2                   Buss, Palmer                     SR IT SPEC     NaN
 3                   Butler, Brad  ASSOC DIR WEB, APP, INFO SERV     NaN
 4                Chan, Michael G                        IT ARCH     NaN
 5              Hart, Mark Smylie          ASST DIR FOR RES SERV     NaN
 6                 Hurst, James R  EXEC DIR, ENGR IT SHARED SERV     NaN
 7                 Le, Thang Hong              SR WEB APP DEVLPR     NaN
 8                      Lee, John             HELP DESK SERV MGR     NaN
 9                 Lowe, Jordan T              SR WEB APP DEVLPR     NaN
 10              Penrose, Frank E                INFRA TEAM LEAD     NaN
 11              Penrose, Frank E                      SYST ENGR     NaN
 12              Penrose, Frank E    Employee Total for All Jobs     NaN
 13             Robbins, Elaine N       ASST DIR FOR INSTRN SERV     NaN
 14              Taraszka, Paul J            SR LINUX SYST ADMNR     NaN

    Empl Class  Present FTE  Proposed FTE Present Salary Proposed Salary
 0          BA          1.0           1.0     $69,061.00      $71,651.00
 1          BA          0.5           0.5     $36,353.00      $37,898.00
 2          BA          1.0           1.0     $66,655.00      $68,655.00
 3          BA          1.0           1.0    $124,110.00     $128,454.00
 4          BA          1.0           1.0    $113,681.00     $117,940.00
 5          BA          1.0           1.0    $105,717.00     $110,472.00
 6          BA          1.0           1.0    $149,040.00     $155,002.00
 7          BA          1.0           1.0    $111,237.00     $116,797.00
 8          BA          1.0           1.0     $85,432.00      $89,704.00
 9          BA          1.0           1.0    $111,237.00     $115,127.00
 10         BA          0.0           0.0      $2,500.08       $2,500.08
 11         BA          1.0           1.0    $115,000.00     $115,000.00
 12        NaN          1.0           1.0    $117,500.08     $117,500.08
 13         BA          1.0           1.0    $105,000.00     $108,413.00
 14         BA          1.0           1.0     $88,383.00      $88,383.00  ,
          Employee Name       Job Title  Tenure Empl Class  Present FTE  \
 0      Atwood, Kathy J  DIR OF ENGR HR     NaN         BA          1.0
 1  Ozier, Sarah Leanne  DIR OF ENGR HR     NaN         BA          1.0

    Proposed FTE Present Salary Proposed Salary
 0           1.0    $114,400.00     $120,120.00
 1           1.0    $107,000.00     $112,350.00  ,
           Employee Name                       Job Title Tenure Empl Class  \
 0        Allison, James                      ASSOC PROF      A         AA
 1        Allison, James  JERRY S DOBROVOLNY FAC SCHOLAR    NaN         AA
 2        Allison, James     Employee Total for All Jobs    NaN        NaN
 3     Bashir, Masooda N                      ASSOC PROF    NaN         AA
 4     Bashir, Masooda N     Employee Total for All Jobs    NaN        NaN
 ..                  ...                             ...    ...        ...
 81          Wang, Qiong        ARTHUR DAVIS FAC SCHOLAR    NaN         AA
 82          Wang, Qiong                      ASSOC PROF      A         AA
 83          Wang, Qiong     Employee Total for All Jobs    NaN        NaN
 84  Wooldridge, Abigail                       ASST PROF      P         AA
 85  Wooldridge, Abigail     Employee Total for All Jobs    NaN        NaN

     Present FTE  Proposed FTE Present Salary Proposed Salary
 0           1.0           1.0    $122,876.00     $127,901.00
 1           0.0           0.0          $0.00           $0.00
 2           1.0           1.0    $122,876.00     $127,901.00
 3           0.0           0.0          $0.00           $0.00
 4           1.0           1.0    $109,325.73     $113,695.00
 ..          ...           ...            ...             ...
 81          0.0           0.0          $0.00           $0.00
 82          1.0           1.0    $141,412.00     $146,368.00
 83          1.0           1.0    $141,412.00     $146,368.00
 84          1.0           1.0    $107,665.00     $112,068.00
 85          1.0           1.0    $107,665.00     $112,068.00

 [86 rows x 8 columns],
              Employee Name                    Job Title  Tenure Empl Class  \
 0        Abdelzaher, Tarek                    PROF, ITI     NaN         AA
 1        Abdelzaher, Tarek  Employee Total for All Jobs     NaN        NaN
 2           Adve, Sarita V                    PROF, ITI     NaN         AA
 3           Adve, Sarita V  Employee Total for All Jobs     NaN        NaN
 4    Adve, Vikram Sadanand                    PROF, ITI     NaN         AA

In [10]:
df_college[5]

,Employee Name,Job Title,Tenure,Empl Class,Present FTE,Proposed FTE,Present Salary,Proposed Salary
0,"Abdelzaher, Tarek",PROF,A,AA,1.0,1.0,"$220,000.00","$228,800.00"
1,"Abdelzaher, Tarek",Employee Total for All Jobs,NaN,NaN,1.0,1.0,"$220,000.00","$228,800.00"
2,"Adve, Sarita V",PROF,A,AA,1.0,1.0,"$230,000.00","$240,000.00"
3,"Adve, Sarita V",Employee Total for All Jobs,NaN,NaN,1.0,1.0,"$230,000.00","$240,000.00"
4,"Adve, Vikram Sadanand",PROF,A,AA,1.0,1.0,"$230,000.00","$240,000.00"
...,...,...,...,...,...,...,...,...
308,"Zhao, Han",Employee Total for All Jobs,NaN,NaN,1.0,1.0,"$136,000.00","$141,440.00"
309,"Zike, Heather",UGRAD PRGM COORD & ACAD ADVR,NaN,BA,1.0,1.0,"$65,487.40","$68,106.40"
310,"Zilles, Craig",PROF,A,AA,1.0,1.0,"$185,000.00","$192,400.00"
311,"Zilles, Craig",SEVERNS FAC SCHOLAR,NaN,AA,0.0,0.0,$0.00,$0.00
312,"Zilles, Craig",Employee Total for All Jobs,NaN,NaN,1.0,1.0,"$185,000.00","$192,400.00"

In [5]:
from time import sleep


dfs = []

for url in urlList:
  x = pd.read_html(url)
  college_df = x[0]
  college = college_df.iloc[0, 0]
  print(college)
  college.split(" - ")
  college_code, college_name = college.split(" - ")

  college_df = college_df.drop(index=[0])
  college_df["College Code"] = college_code
  college_df["College Name"] = college_name

  college_df = college_df.apply(f, axis=1)
  college_df = college_df.dropna(subset=["Department Code"])
  dfs.append(college_df)
  sleep(5)

Allison, James

ValueError: not enough values to unpack (expected 2, got 1)

In [62]:
df = pd.concat(dfs)
df.to_csv("graybook-2024.csv", index=False)